Propellor.Types.Info: add missing import for 'cast'
The change fixes the following build failure on ghc-8.2.1:

    [  6 of 160] Compiling Propellor.Types.Info ( src/Propellor/Types/Info.hs, dist/dist-sandbox-2ceaa3c0/build/Propellor/Types/Info.o )
    src/Propellor/Types/Info.hs:38:34: error:
        • Variable not in scope: cast :: v1 -> Maybe v
        • Perhaps you meant one of these:
            data constructor ‘Last’ (imported from Data.Monoid),
            ‘last’ (imported from Prelude)
       |
    38 | extractInfoEntry (InfoEntry v) = cast v
       |                                  ^^^^

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>